### ISSUE TITLE
Unwanted comma added after the negative prompt

### ISSUE THREAD

**Issue by brayevalerien** [brayevalerien/Prompt-retreiver#2]
When retreiving the informations from an image generated with Fooocus, a comma followed by a space are added at the end of the negative prompt.
![image](https://github.com/brayevalerien/Prompt-retreiver/assets/60972074/156313f7-e936-4836-b193-1e6ad40dcf61)

The ", " at the end should be removed.

**Comment by Airop** [comment]
I would like to work on that task!

**Comment by brayevalerien** [comment]
Sure, thanks for proposing. I've only found this issue on Fooocus images but I haven't tried with images from Automatic1111 so you might want to do some tests if you want to keep compatibility with both generators.

**Comment by Airop** [comment]
Could you perhaps add the example picture of the truck in the jungle to the Git so I can fix the comma issue properly? (I don't have the paid version of foocus)

So far for Automatic1111 (web application) this issue doesn't appear.

**Comment by brayevalerien** [comment]
Here it is, although I'm not sure metadata are kept in the image when uploading to GitHub. Tell me if it's not the case.
![2024-04-19_17-17-03_9606](https://github.com/brayevalerien/Prompt-retreiver/assets/60972074/088031d5-9dd0-494b-9a8e-a5ee0b108f8f)
Fooocus is entirely free and there is no need for a paid version if you want to save the generation data inside the image, it only requires you to check a box in the developpers settings. But for this image I used [Fooocus Lite](https://github.com/brayevalerien/Fooocus-Lite), which has this option enabled by default.
Great to know that Automatic results are not affected! I need to setup automated tests

**Comment by brayevalerien** [comment]
Fixed by #3 , thanks @Airop !
